import { LegalPage, legalMetadata } from "@/components/legal/legal-page";
import { legalSiteConfig as config } from "@/config/legal";
export const metadata = legalMetadata("Privacy Policy", "How MaorTrades processes information across email, checkout, analytics, support, and consent preferences.");
export default function PrivacyPage() { const operator = config.legalOperatorName ? `${config.brandName} is operated by ${config.legalOperatorName}.` : `${config.brandName} is an educational publishing website.`; const contact = config.privacyEmail ? `Privacy questions may be sent to ${config.privacyEmail}.` : "A dedicated privacy contact must be configured before launch."; return <LegalPage title="PRIVACY POLICY" introduction="This policy explains the information MaorTrades may process when you browse educational content, request emails, begin checkout, purchase through Lemon Squeezy, or contact support." sections={[
  { title: "Who operates MaorTrades", paragraphs: [operator] },
  { title: "Information the site may process", paragraphs: ["Depending on how you use the site, MaorTrades may process an email address supplied for the Letter or an eligible Free Resource, consent preferences, technical request and security logs, consented page and interaction analytics, checkout product context, limited order context from verified Lemon Squeezy webhooks, and information you voluntarily include in support communications."] },
  { title: "Payments and digital purchases", paragraphs: ["Lemon Squeezy processes checkout, payment, receipts, order retrieval, and paid-file access. MaorTrades does not directly collect or store complete payment-card details. Verified webhooks provide limited operational order context; Lemon Squeezy operates its systems under its own policies."] },
  { title: "Newsletter and resource email", paragraphs: ["Resend supports subscription and permitted email delivery. The MaorTrades Letter uses double opt-in. Marketing email can be unsubscribed from. A resource form may also subscribe the requester only where that is disclosed before submission."] },
  { title: "Analytics, Pinterest, and consent", paragraphs: ["Google Analytics browser tracking operates only after Analytics consent. Pinterest measurement operates only after Marketing consent. Preferences can be changed through Footer Cookie Settings. Pinterest hashed-email matching is not enabled or implemented in the current architecture."] },
  { title: "How information is used", paragraphs: ["Information may be used to deliver requested email, manage subscription consent, operate checkout, verify provider webhooks, provide support, understand site use with permission, measure marketing with permission, protect security, and improve educational navigation."] },
  { title: "Service providers and international processing", paragraphs: ["Current service providers may include Lemon Squeezy, Resend, Google Analytics when configured, and Pinterest when configured. A hosting provider has not yet been selected. Providers may process information in other countries according to their systems and agreements; no unsupported transfer-compliance claim is made here."] },
  { title: "Retention and choices", paragraphs: ["Information is retained only as reasonably necessary for its stated purpose, operational security, disputes, and applicable obligations. Exact retention rules require legal and operational review. Depending on applicable law, you may have choices or rights concerning personal information; contact MaorTrades to make an inquiry."] },
  { title: "Children and policy changes", paragraphs: ["MaorTrades is intended for an adult trading-education audience and is not directed to children. The policy may be updated when services or practices change; material changes will be communicated through an appropriate site notice or another reasonable method."] },
  { title: "Contact", paragraphs: [contact] },
]}/>; }
