import Link from "next/link"; import { LegalPage, legalMetadata } from "@/components/legal/legal-page"; import { legalSiteConfig as config } from "@/config/legal";
export const metadata = legalMetadata("Terms of Use and Sale", "Draft terms governing MaorTrades educational content and digital purchases.");
export default function TermsPage() { const sections = [
 { title:"Acceptance and services", paragraphs:["By using MaorTrades, you agree to these draft terms as finalized for launch. MaorTrades provides educational Books, Collections, Journal articles, Free Resources, and the MaorTrades Letter."] },
 { title:"Educational purpose", paragraphs:[<>Content is general education, not personalized financial advice. Read the <Link href="/disclaimer">Trading and Educational Disclaimer</Link>.</>] },
 { title:"Digital purchases", paragraphs:["Lemon Squeezy processes checkout and provides receipts and paid-content access. Review product descriptions and provider-displayed prices before purchase. A Collection may include multiple Book files."] },
 { title:"Personal-use license", paragraphs:["A purchase is intended to grant a personal, limited, non-exclusive, non-transferable right to use the digital content. Copyright remains with the author or applicable rights holder. Resale, redistribution, public uploading, and unauthorized sharing are prohibited. Final license wording requires legal review."] },
 { title:"Intellectual property and acceptable use", paragraphs:["MaorTrades text, Books, covers, diagrams, Articles, Resources, visual materials, and branding are protected to the extent provided by applicable law. Do not copy or redistribute protected material without permission, disrupt or interfere with security, use the service unlawfully, or perform abusive scraping. Normal linking and legitimate search indexing are not prohibited."] },
 { title:"Pricing, availability, refunds, and third parties", paragraphs:[<>Prices and availability may change before purchase but do not retroactively alter a completed order. Refund requests are governed by the <Link href="/refund-policy">Refund Policy</Link>. Lemon Squeezy, Resend, Google, Pinterest, and linked sites operate under their own terms where applicable.</>] },
 { title:"No guarantee of results", paragraphs:["Educational content does not guarantee profits, consistency, funded-account qualification, evaluation success, payouts, or avoidance of loss."] },
 { title:"Liability draft", paragraphs:["To the extent permitted by applicable law, MaorTrades is not intended to be liable for trading decisions or losses made in reliance on general educational content. This limitation is deliberately conservative and requires professional review for applicable consumer rights and jurisdiction."] },
 ...(config.governingLawLabel ? [{ title:"Governing law", paragraphs:[config.governingLawLabel] }] : []),
 { title:"Changes and contact", paragraphs:[`Terms may be updated as services change. ${config.supportEmail ? `Questions may be sent to ${config.supportEmail}.` : "A support contact must be configured before launch."}`] }
]; return <LegalPage title="TERMS OF USE AND SALE" introduction="These draft terms describe use of the MaorTrades educational website and digital products. They must be reviewed for the markets in which the store will operate." sections={sections}/>; }
