import { LegalPage, legalMetadata } from "@/components/legal/legal-page";
export const metadata=legalMetadata("Cookie Policy","How necessary, analytics, and marketing storage are controlled on MaorTrades.");
export default function CookiePolicyPage(){return <LegalPage title="COOKIE POLICY" introduction="MaorTrades uses a first-party preference cookie and loads optional analytics or marketing providers only after the corresponding choice." sections={[
 {title:"Consent categories",paragraphs:["Necessary storage is always active for site operation, security, checkout, essential forms, Purchase Context, and consent preferences. Analytics helps understand educational-content use. Marketing permits Pinterest advertising attribution and campaign measurement."]},
 {title:"First-party preference",paragraphs:["The versioned maortrades_consent cookie records only necessary, analytics, and marketing choices with an update timestamp. It contains no email, analytics client ID, or customer identifier. It uses SameSite=Lax, a site-wide path, and Secure on HTTPS. Its current configured duration is 180 days; this is an operational setting, not a legal claim."]},
 {title:"Google Analytics",paragraphs:["GA4 loads only after Analytics consent and only when configured. It may create provider identifiers and receives page or meaningful interaction events. MaorTrades does not send email addresses or payment-card information to GA4."]},
 {title:"Pinterest",paragraphs:["Pinterest Tag loads only after Marketing consent and only when configured. A documented Pinterest click identifier may be used for attribution after consent. Browser enhanced matching and hashed-email matching are not enabled or implemented."]},
 {title:"Changing preferences",paragraphs:["Use Cookie Settings in the Footer at any time. Revoking analytics stops future calls and updates Google state where loaded. Revoking marketing causes a controlled reload so Pinterest no longer operates. The site does not guess at or automatically delete provider-created cookies; that behavior requires further policy or consent-platform review."]}
]}/>}
