"use client";

import { useEffect, useId, useRef, useState } from "react";
import type { ConsentPreferences } from "@/lib/analytics/consent";

export function ConsentBanner({ open, managed, consent, onSave, onClose }: { open: boolean; managed: boolean; consent: ConsentPreferences; onSave: (analytics: boolean, marketing: boolean) => void; onClose: () => void }) {
  const [manage, setManage] = useState(managed); const [analytics, setAnalytics] = useState(consent.analytics); const [marketing, setMarketing] = useState(consent.marketing); const titleId = useId(); const panel = useRef<HTMLDivElement>(null);
  useEffect(() => { if (open) setTimeout(() => { setManage(managed); setAnalytics(consent.analytics); setMarketing(consent.marketing); panel.current?.focus(); }, 0); }, [open, managed, consent]);
  useEffect(() => { const escape = (event: KeyboardEvent) => { if (event.key === "Escape" && managed) onClose(); }; document.addEventListener("keydown", escape); return () => document.removeEventListener("keydown", escape); }, [managed, onClose]);
  if (!open) return null;
  return <div className="fixed inset-0 z-[100] flex items-end bg-navy/35 p-3 sm:items-center sm:justify-center" role="presentation"><div ref={panel} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby={titleId} className="max-h-[90vh] w-full max-w-2xl overflow-y-auto border border-border bg-surface p-6 shadow-editorial sm:p-8">
    <p className="label text-gold">PRIVACY PREFERENCES</p><h2 id={titleId} className="heading-md mt-3 text-navy">CHOOSE HOW MAORTRADES MEASURES VISITS.</h2><p className="body-sm mt-4 text-muted-foreground">Necessary storage keeps the site and your preferences working. Optional analytics and Pinterest measurement remain off until you choose otherwise.</p>
    {manage ? <fieldset className="mt-6 grid gap-3"><legend className="sr-only">Optional consent categories</legend><div className="border border-border p-4"><p className="label text-navy">Necessary Cookies — Always active</p><p className="body-sm mt-2 text-muted-foreground">Used for site operation, security, checkout, forms, and consent preferences.</p></div><Preference checked={analytics} onChange={setAnalytics} title="Analytics" description="Helps MaorTrades understand how visitors use the website and educational content."/><Preference checked={marketing} onChange={setMarketing} title="Marketing" description="Allows Pinterest measurement for advertising attribution and campaign performance."/></fieldset> : null}
    <div className="mt-7 flex flex-col gap-3 sm:flex-row sm:flex-wrap"><button className="min-h-12 border border-navy bg-navy px-5 text-sm font-semibold text-ivory focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-gold" onClick={() => onSave(true, true)}>Accept All</button><button className="min-h-12 border border-navy/30 px-5 text-sm font-semibold text-navy focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-gold" onClick={() => onSave(false, false)}>Reject Optional</button>{manage ? <button className="min-h-12 border border-gold px-5 text-sm font-semibold text-navy focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-gold" onClick={() => onSave(analytics, marketing)}>Save Preferences</button> : <button className="min-h-12 px-3 text-sm font-semibold text-navy underline underline-offset-4" onClick={() => setManage(true)}>Manage Preferences</button>}{managed ? <button className="min-h-12 px-3 text-sm text-muted-foreground" onClick={onClose}>Close</button> : null}</div>
  </div></div>;
}
function Preference({ checked, onChange, title, description }: { checked: boolean; onChange: (value: boolean) => void; title: string; description: string }) { const id = useId(); return <label htmlFor={id} className="flex cursor-pointer gap-4 border border-border p-4"><input id={id} type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} className="mt-1 size-5 accent-navy"/><span><span className="label text-navy">{title}: {checked ? "Enabled" : "Disabled"}</span><span className="body-sm mt-2 block text-muted-foreground">{description}</span></span></label>; }
